#!/bin/bash
# Demo script for Aliaser - DO NOT USE WITH REAL PASSWORDS

set -e

BINARY="./target/release/aliaser"

echo "======================================"
echo "   Aliaser Demo Script"
echo "======================================"
echo ""
echo "⚠️  WARNING: This is a demo only!"
echo "    Your actual vault will NOT be affected."
echo ""
echo "This demo will show you:"
echo "  1. Initializing a vault"
echo "  2. Adding identities"
echo "  3. Listing identities"
echo "  4. Viewing identity details"
echo "  5. Exporting backup"
echo ""
read -p "Press Enter to continue..."

# Build if needed
if [ ! -f "$BINARY" ]; then
    echo ""
    echo "Building Aliaser..."
    cargo build --release
fi

# Backup existing vault if it exists
if [ -f "$HOME/.aliaser.vault" ]; then
    echo ""
    echo "Backing up your existing vault..."
    mv "$HOME/.aliaser.vault" "$HOME/.aliaser.vault.bak"
    mv "$HOME/.aliaser.config" "$HOME/.aliaser.config.bak"
    echo "✓ Existing vault backed up"
fi

echo ""
echo "======================================"
echo "Step 1: Initialize Vault"
echo "======================================"
echo ""
echo "Master password: demo1234"
echo "Confirm password: demo1234"
echo ""

# Note: In a real demo, you'd need interactive input
# This is just showing the commands

echo "Command: $BINARY init"
echo "(You would enter 'demo1234' as the master password)"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "======================================"
echo "Step 2: Add Identity - GitHub"
echo "======================================"
echo ""
echo "This would prompt you for:"
echo "  Service name: GitHub"
echo "  Username: demo_user"
echo "  Password: [auto-generated]"
echo "  Email: demo@example.com"
echo "  Alias: demouser"
echo "  Personal info: No"
echo "  Notes: Demo GitHub account"
echo ""
echo "Command: $BINARY add"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "======================================"
echo "Step 3: Add Identity - Gmail"
echo "======================================"
echo ""
echo "This would prompt you for:"
echo "  Service name: Gmail"
echo "  Username: demo@gmail.com"
echo "  Password: [auto-generated]"
echo "  Email: demo@gmail.com"
echo "  Alias: demo.user"
echo "  Personal info: Yes"
echo "    First Name: Demo"
echo "    Last Name: User"
echo "    Birthdate: 1990-01-01"
echo "  Notes: Personal email"
echo ""
echo "Command: $BINARY add"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "======================================"
echo "Step 4: List All Identities"
echo "======================================"
echo ""
echo "Command: $BINARY list"
echo ""
echo "Expected output:"
echo "  Stored Identities:"
echo ""
echo "    1. GitHub"
echo "    2. Gmail"
echo ""
echo "  Total: 2"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "======================================"
echo "Step 5: View Identity Details"
echo "======================================"
echo ""
echo "Command: $BINARY get GitHub"
echo ""
echo "Expected output:"
echo "  Identity: GitHub"
echo "  =================================================="
echo ""
echo "  Credentials:"
echo "    Username: demo_user"
echo "    Password: Xy9#mK2$pL7@qR4&"
echo "    Email: demo@example.com"
echo "    Alias: demouser"
echo ""
echo "  Notes:"
echo "    Demo GitHub account"
echo ""
echo "  Metadata:"
echo "    Created: 2026-01-01 10:30:00"
echo "    Updated: 2026-01-01 10:30:00"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "======================================"
echo "Step 6: Export Backup"
echo "======================================"
echo ""
echo "Command: $BINARY export demo-backup.vault"
echo ""
echo "Expected output:"
echo "  ✓ Vault exported to: demo-backup.vault"
echo "  The exported file is encrypted with your master password."
echo ""
read -p "Press Enter to continue..."

echo ""
echo "======================================"
echo "Step 7: Update Identity"
echo "======================================"
echo ""
echo "Command: $BINARY update GitHub"
echo ""
echo "You could update:"
echo "  - Username"
echo "  - Password"
echo "  - Email"
echo "  - Personal information"
echo "  - Notes"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "======================================"
echo "Step 8: Delete Identity"
echo "======================================"
echo ""
echo "Command: $BINARY delete OldService"
echo ""
echo "You'll be asked to confirm:"
echo "  Delete identity for 'OldService'?"
echo "  This action cannot be undone!"
echo ""
echo "  Confirm deletion (y/n): y"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "======================================"
echo "Step 9: Change Master Password"
echo "======================================"
echo ""
echo "Command: $BINARY change-master"
echo ""
echo "You'll be prompted for:"
echo "  Current master password: [enter current]"
echo "  New master password: [enter new]"
echo "  Confirm password: [confirm new]"
echo ""
echo "All data will be re-encrypted with new password."
echo ""
read -p "Press Enter to continue..."

echo ""
echo "======================================"
echo "Demo Complete!"
echo "======================================"
echo ""
echo "Key Features Demonstrated:"
echo "  ✓ Vault initialization with master password"
echo "  ✓ Adding identities with credentials"
echo "  ✓ Storing personal information"
echo "  ✓ Listing all stored services"
echo "  ✓ Viewing identity details"
echo "  ✓ Exporting encrypted backups"
echo "  ✓ Updating existing identities"
echo "  ✓ Deleting identities"
echo "  ✓ Changing master password"
echo ""
echo "Security Features:"
echo "  🔒 AES-256-GCM encryption"
echo "  🔑 Argon2id key derivation"
echo "  💾 All data stored locally"
echo "  🚫 No network requests"
echo "  🧹 Sensitive data zeroized"
echo ""
echo "To try it yourself:"
echo "  1. Run: $BINARY init"
echo "  2. Follow the prompts"
echo "  3. Store your credentials securely!"
echo ""

# Restore original vault if it existed
if [ -f "$HOME/.aliaser.vault.bak" ]; then
    echo "Restoring your original vault..."
    rm -f "$HOME/.aliaser.vault" "$HOME/.aliaser.config"
    mv "$HOME/.aliaser.vault.bak" "$HOME/.aliaser.vault"
    mv "$HOME/.aliaser.config.bak" "$HOME/.aliaser.config"
    echo "✓ Original vault restored"
fi

echo ""
echo "Happy secure password management! 🔐"
